### ISSUE TITLE
Security issue: Account hijacking possible if email address can be changed in LDAP

### ISSUE THREAD

**Issue by thegcat** [Sohalt/pretix-ldap#8]
Currently this plugin uses the user's email address as its primary key and doesn't check if subsequent logins are performed by the same user that created the account in Pretix. This might also be problematic if the LDAP allows for duplicate email addresses in the search tree as the returned LDAP object might not be stable/always the same.

It should at least be made very clear in the plugin's documentation that this plugin expects the email address attribute to not be changeable in the LDAP server.

Furthermore, a mitigation against account hijacking as described above would be to store either the LDAP UID, the LDAP DN or any other configurable LDAP attribute that the administrators knows to be not user changeable, to store it in Pretix alongside the user's email address on creating the Pretix user account out of LDAP. This immutable attribute can then be compared on subsequent logins to ensure that the user that created the account is still the one trying to log in.

**Comment by Sohalt** [comment]
Thanks for raising the issue.
Storing the LDAP UID or LDAP DN with the user would require changing the data model, which I'm not sure a plugin can do.

Pretix itself uses email addresses as a unique way to identify users.

It is generally a pretty bad idea to transfer email addresses to someone else, because most password reset mechanisms send a new password to the registered email address. It is also bad to allow users to change their email address in LDAP without verifying that the user actually controls that email address. The attack scenario does not work when the owner of an email address keeps ownership and the LDAP directory correctly verifies ownership. Given this and the difficulty of changing the model, I don't think I will fix this.

Feel free to prototype a PR however.

**Comment by raphaelm** [comment]
There's work going on in pretix to make this easy to fix: https://github.com/pretix/pretix/pull/2466

**Comment by thegcat** [comment]
> Thanks for raising the issue. Storing the LDAP UID or LDAP DN with the user would require changing the data model, which I'm not sure a plugin can do.

A plugin would be able to, but there's a builtin mechanism being worked on to alleviate this need https://github.com/pretix/pretix/pull/2466

> Pretix itself uses email addresses as a unique way to identify users.

Correct.

> It is generally a pretty bad idea to transfer email addresses to someone else, because most password reset mechanisms send a new password to the registered email address. It is also bad to allow users to change their email address in LDAP without verifying that the user actually controls that email address. The attack scenario does not work when the owner of an email address keeps ownership and the LDAP directory correctly verifies ownership. 

This is not about actively transferring ownership of the email address but about e.g. one user being removed from the LDAP (account closed, gdpr removal, what have you) and another user being able to get an account with the same email address.

Anyways, once the dust has settled with the core implementation I'll see about a PR, yes.

**Comment by Sohalt** [comment]
Thanks! Good to see that addressed in pretix itself. This will indeed make fixing this easy.

**Comment by raphaelm** [comment]
https://github.com/pretix/pretix/pull/2466 has been merged

**Comment by thegcat** [comment]
I have started a PR to add the appropriate support.

@Sohalt could you point me at how to run the tests?

**Comment by Sohalt** [comment]
Thanks!
```
cd src/tests
pip install -r requirements.txt
pytest
```
should to the trick (you also need docker on the system).

See https://github.com/Sohalt/pretix-ldap/blob/master/.github/workflows/ci.yml#L8
